name: .NET Core

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --configuration Release -o '${{ github.workspace }}/published'
      working-directory: 'src/Benday.VsliveVirtual.WebUi'
    - name: Get current date
      run: echo "::set-output name=rundate::$(date -u)"
    - name: Set version message in appsettings.json
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathtosettingsfile: '${{ github.workspace }}/published/appsettings.json'
        keyname1: 'VersionMessage'
        valuetoset: '${{ github.workflow }} - ${{ github.run_id }} - ${{ github.sha }} - ${{env.rundate}}'        
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: "vslvirtual1"
        publish-profile: ${{ secrets.AZUREWEBAPPPUBLISHPROFILE  }}
        package: '${{ github.workspace }}/published'
